spring:
  application:
    name: grpc-server
  datasource:
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://10.33.108.63:6606/uc?characterEncoding=UTF-8
    username: qa
logging:
  level:
    com:
      dalaoyang:
        dao:
          UserMapper: debug
mybatis-plus:
  mapper-locations: classpath*:mapper/*Mapper.xml
  type-aliases-package: com.chenhaibo.model
  configuration:
    map-underscore-to-camel-case: true
server:
  port: 1111
  tomcat:
    uri-encoding: utf-8
grpc:
  server:
    port: 9898
gateway:
  server:
    port: 8080
registry:
  zkServers: 10.33.107.16:2800