spring:
  application:
    name: grpc-server
  datasource:
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://10.10.35.13:6606/uc?characterEncoding=UTF-8
    username: qa
logging:
  level:
    com:
      dalaoyang:
        dao:
          UserMapper: debug
mybatis-plus:
  mapper-locations: classpath*:mapper/*Mapper.xml
  type-aliases-package: com.chenhaibo.model
server:
  port: 8088
  tomcat:
    uri-encoding: utf-8
grpc:
  server:
    port: 9898
registry:
  servers: 10.33.107.16:2800
  nodepath: /jichu/grpc
  username: jichu
  password: McBuai6Ken