// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: JobFacade.proto

package com.chenhaibo.grpc.jobfacade;

public final class JobFacadeOuterClass {
  private JobFacadeOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_chenhaibo_grpc_jobfacade_JobParam_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_chenhaibo_grpc_jobfacade_JobParam_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_chenhaibo_grpc_jobfacade_JobResult_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_chenhaibo_grpc_jobfacade_JobResult_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017JobFacade.proto\022\034com.chenhaibo.grpc.jo" +
      "bfacade\"\026\n\010JobParam\022\n\n\002id\030\001 \001(\t\"(\n\tJobRe" +
      "sult\022\n\n\002id\030\001 \001(\t\022\017\n\007jobCode\030\002 \001(\t2j\n\tJob" +
      "Facade\022]\n\ngetJobById\022&.com.chenhaibo.grp" +
      "c.jobfacade.JobParam\032\'.com.chenhaibo.grp" +
      "c.jobfacade.JobResultB\002P\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_chenhaibo_grpc_jobfacade_JobParam_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_chenhaibo_grpc_jobfacade_JobParam_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_chenhaibo_grpc_jobfacade_JobParam_descriptor,
        new java.lang.String[] { "Id", });
    internal_static_com_chenhaibo_grpc_jobfacade_JobResult_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_chenhaibo_grpc_jobfacade_JobResult_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_chenhaibo_grpc_jobfacade_JobResult_descriptor,
        new java.lang.String[] { "Id", "JobCode", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
