// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: JobFacade.proto

package com.chenhaibo.grpc.jobfacade;

public interface JobParamOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.chenhaibo.grpc.jobfacade.JobParam)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string id = 1;</code>
   */
  java.lang.String getId();
  /**
   * <code>string id = 1;</code>
   */
  com.google.protobuf.ByteString
      getIdBytes();
}
