// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: JobFacade.proto

package com.chenhaibo.grpc.jobfacade;

public interface JobResultOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.chenhaibo.grpc.jobfacade.JobResult)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string id = 1;</code>
   */
  java.lang.String getId();
  /**
   * <code>string id = 1;</code>
   */
  com.google.protobuf.ByteString
      getIdBytes();

  /**
   * <code>string jobCode = 2;</code>
   */
  java.lang.String getJobCode();
  /**
   * <code>string jobCode = 2;</code>
   */
  com.google.protobuf.ByteString
      getJobCodeBytes();
}
