// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: UserFacade.proto

package com.chenhaibo.grpc.userfacade;

public interface UserResultOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.chenhaibo.grpc.userfacade.UserResult)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string id = 1;</code>
   */
  java.lang.String getId();
  /**
   * <code>string id = 1;</code>
   */
  com.google.protobuf.ByteString
      getIdBytes();

  /**
   * <code>string name = 2;</code>
   */
  java.lang.String getName();
  /**
   * <code>string name = 2;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();
}
