// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: UserFacade.proto

package com.chenhaibo.grpc.userfacade;

public interface UserParamOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.chenhaibo.grpc.userfacade.UserParam)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string name = 1;</code>
   */
  java.lang.String getName();
  /**
   * <code>string name = 1;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();
}
