// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: UserFacade.proto

package com.chenhaibo.grpc.userfacade;

public final class UserFacadeOuterClass {
  private UserFacadeOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_chenhaibo_grpc_userfacade_UserParam_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_chenhaibo_grpc_userfacade_UserParam_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_chenhaibo_grpc_userfacade_UserResult_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_chenhaibo_grpc_userfacade_UserResult_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020UserFacade.proto\022\035com.chenhaibo.grpc.u" +
      "serfacade\"\031\n\tUserParam\022\014\n\004name\030\001 \001(\t\"&\n\n" +
      "UserResult\022\n\n\002id\030\001 \001(\t\022\014\n\004name\030\002 \001(\t2l\n\n" +
      "UserFacade\022^\n\007getUser\022(.com.chenhaibo.gr" +
      "pc.userfacade.UserParam\032).com.chenhaibo." +
      "grpc.userfacade.UserResultB\002P\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_chenhaibo_grpc_userfacade_UserParam_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_chenhaibo_grpc_userfacade_UserParam_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_chenhaibo_grpc_userfacade_UserParam_descriptor,
        new java.lang.String[] { "Name", });
    internal_static_com_chenhaibo_grpc_userfacade_UserResult_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_chenhaibo_grpc_userfacade_UserResult_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_chenhaibo_grpc_userfacade_UserResult_descriptor,
        new java.lang.String[] { "Id", "Name", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
