spring:
  mvc:
    static-path-pattern: /static/**
    view:
      prefix: classpath:/templates/
      suffix: .html
  application:
    name: grpc-client
server:
  port: 8888
  tomcat:
    uri-encoding: utf-8
registry:
  servers: 10.33.107.16:2800
  nodepath: /jichu/grpc
  username: jichu
  password: McBuai6Ken