spring:
  mvc:
    static-path-pattern: /static/**
    view:
      prefix: classpath:/templates/
      suffix: .html
  application:
    name: grpc-client
server:
  port: 1110
  tomcat:
    uri-encoding: utf-8
registry:
  linkerdAddress: 127.0.0.1:4143